export interface MasterTrackInfo {
  audioUrl: string;
  duration: number;
  filename: string;
  sunoUrl: string;
  label: string;
}

export const MASTER_TRACKS: Record<number, MasterTrackInfo> = {
  1: {
    audioUrl: '/audio/week_1.mp3',
    duration: 607,
    filename: 'SacredSteps_W01_The_First_Step_Eli_Hargrove.mp3',
    sunoUrl: 'https://suno.com/s/7FSGyO91u0Smadt3',
    label: 'Original Master: “The First Step” (10:07)',
  },
  2: {
    audioUrl: '/audio/week_2.mp3',
    duration: 670,
    filename: 'SacredSteps_W02_Shattered_Armor_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/song/f3ed842f-2a7d-4acc-a0c6-155d4bd963a4',
    label: 'Original Master: “Shattered Armor (Grace Enough)” (11:10)',
  },
  3: {
    audioUrl: '/audio/week_3.mp3',
    duration: 649,
    filename: 'SacredSteps_W03_Shoulder_to_Shoulder_Kojo_Bright.mp3',
    sunoUrl: 'https://suno.com/search?q=Shoulder%20to%20Shoulder%20Kojo%20Bright',
    label: 'Original Master: “Shoulder to Shoulder” (10:49)',
  },
  4: {
    audioUrl: '/audio/week_4.mp3',
    duration: 691,
    filename: 'SacredSteps_W04_Laugh_at_Tomorrow_Zaria_Lumen.mp3',
    sunoUrl: 'https://suno.com/search?q=Laugh%20at%20Tomorrow%20Zaria%20Lumen',
    label: 'Original Master: “Laugh at Tomorrow” (11:31)',
  },
  5: {
    audioUrl: '/audio/week_5.mp3',
    duration: 800,
    filename: 'SacredSteps_W05_River_That_Never_Runs_Dry_Naledi_Groove.mp3',
    sunoUrl: 'https://suno.com/search?q=River%20That%20Never%20Runs%20Dry%20Naledi%20Groove',
    label: 'Original Master: “River That Never Runs Dry” (13:20)',
  },
  6: {
    audioUrl: '/audio/week_6.mp3',
    duration: 860,
    filename: 'SacredSteps_W06_The_Distance_You_Made_Mose_Ardell.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Distance%20You%20Made%20Mose%20Ardell',
    label: 'Original Master: “The Distance You Made” (14:20)',
  },
  7: {
    audioUrl: '/audio/week_7.mp3',
    duration: 688,
    filename: 'SacredSteps_W07_What_the_Fall_Taught_Me_Kwame_Uplift.mp3',
    sunoUrl: 'https://suno.com/search?q=What%20the%20Fall%20Taught%20Me%20Kwame%20Uplift',
    label: 'Original Master: “What the Fall Taught Me” (11:28)',
  },
  8: {
    audioUrl: '/audio/week_8.mp3',
    duration: 820,
    filename: 'SacredSteps_W08_Temple_Restored_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Temple%20Restored%20Simone%20Reyner',
    label: 'Original Master: “Temple Restored” (13:40)',
  },
  9: {
    audioUrl: '/audio/week_9.mp3',
    duration: 180,
    filename: 'SacredSteps_W09_Above_the_Noise_Femi_Highgate.mp3',
    sunoUrl: 'https://suno.com/search?q=Above%20the%20Noise%20Femi%20Highgate',
    label: 'Original Master: “Above the Noise” (3:00)',
  },
  10: {
    audioUrl: '/audio/week_10.mp3',
    duration: 667,
    filename: 'SacredSteps_W10_Deeper_Roots_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=Deeper%20Roots%20Judah%20Rell',
    label: 'Original Master: “Deeper Roots” (11:07)',
  },
  11: {
    audioUrl: '/audio/week_11.mp3',
    duration: 874,
    filename: 'SacredSteps_W11_The_Life_You_Meant_Zaria_Lumen.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Life%20You%20Meant%20Zaria%20Lumen',
    label: 'Original Master: “The Life You Meant” (14:34)',
  },
  12: {
    audioUrl: '/audio/week_12.mp3',
    duration: 836,
    filename: 'SacredSteps_W12_The_Door_Stayed_Open_Mose_Ardell.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Door%20Stayed%20Open%20Mose%20Ardell',
    label: 'Original Master: “The Door Stayed Open” (13:56)',
  },
  13: {
    audioUrl: '/audio/week_13.mp3',
    duration: 672,
    filename: 'SacredSteps_W13_The_Tables_Set_Again_Eli_Hargrove.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Tables%27%20Set%20Again%20Eli%20Hargrove',
    label: 'Original Master: “The Tables’ Set Again” (11:12)',
  },
  14: {
    audioUrl: '/audio/week_14.mp3',
    duration: 719,
    filename: 'SacredSteps_W14_Hands_of_Purpose_Femi_Highgate.mp3',
    sunoUrl: 'https://suno.com/search?q=Hands%20of%20Purpose%20Femi%20Highgate',
    label: 'Original Master: “Hands of Purpose” (11:59)',
  },
  15: {
    audioUrl: '/audio/week_15.mp3',
    duration: 759,
    filename: 'SacredSteps_W15_Ledger_of_Peace_Naledi_Groove.mp3',
    sunoUrl: 'https://suno.com/search?q=Ledger%20of%20Peace%20Naledi%20Groove',
    label: 'Original Master: “Ledger of Peace” (12:39)',
  },
  16: {
    audioUrl: '/audio/week_16.mp3',
    duration: 732,
    filename: 'SacredSteps_W16_Setting_the_Weight_Down_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Setting%20the%20Weight%20Down%20Simone%20Reyner',
    label: 'Original Master: “Setting the Weight Down” (12:12)',
  },
  17: {
    audioUrl: '/audio/week_17.mp3',
    duration: 832,
    filename: 'SacredSteps_W17_The_Room_Where_Healing_Starts_Kojo_Bright.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Room%20Where%20Healing%20Starts%20Kojo%20Bright',
    label: 'Original Master: “The Room Where Healing Starts” (13:52)',
  },
  18: {
    audioUrl: '/audio/week_18.mp3',
    duration: 817,
    filename: 'SacredSteps_W18_Feathers_in_the_Dawn_Naledi_Groove.mp3',
    sunoUrl: 'https://suno.com/search?q=Feathers%20in%20the%20Dawn%20Naledi%20Groove',
    label: 'Original Master: “Feathers in the Dawn” (13:37)',
  },
  19: {
    audioUrl: '/audio/week_19.mp3',
    duration: 786,
    filename: 'SacredSteps_W19_The_Gavel_Fell_Colt_Ferrin.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Gavel%20Fell%20Colt%20Ferrin',
    label: 'Original Master: “The Gavel Fell” (13:06)',
  },
  20: {
    audioUrl: '/audio/week_20.mp3',
    duration: 640,
    filename: 'SacredSteps_W20_Image_Restored_Kwame_Uplift.mp3',
    sunoUrl: 'https://suno.com/search?q=Image%20Restored%20Kwame%20Uplift',
    label: 'Original Master: “Image Restored” (10:40)',
  },
  21: {
    audioUrl: '/audio/week_21.mp3',
    duration: 800,
    filename: 'SacredSteps_W21_Sanctuary_of_Souls_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Sanctuary%20of%20Souls%20Simone%20Reyner',
    label: 'Original Master: “Sanctuary of Souls” (13:20)',
  },
  22: {
    audioUrl: '/audio/week_22.mp3',
    duration: 898,
    filename: 'SacredSteps_W22_Anchor_in_the_Gale_Mose_Ardell.mp3',
    sunoUrl: 'https://suno.com/search?q=Anchor%20in%20the%20Gale%20Mose%20Ardell',
    label: 'Original Master: “Anchor in the Gale” (14:58)',
  },
  23: {
    audioUrl: '/audio/week_23.mp3',
    duration: 665,
    filename: 'SacredSteps_W23_Milestone_Marker_Kwame_Uplift.mp3',
    sunoUrl: 'https://suno.com/search?q=Milestone%20Marker%20Kwame%20Uplift',
    label: 'Original Master: “Milestone Marker” (11:05)',
  },
  24: {
    audioUrl: '/audio/week_24.mp3',
    duration: 665,
    filename: 'SacredSteps_W24_Table_in_the_Rain_Femi_Highgate.mp3',
    sunoUrl: 'https://suno.com/search?q=Table%20in%20the%20Rain%20Femi%20Highgate',
    label: 'Original Master: “Table in the Rain” (11:05)',
  },
  25: {
    audioUrl: '/audio/week_25.mp3',
    duration: 682,
    filename: 'SacredSteps_W25_Quiet_in_the_Chaos_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=Quiet%20in%20the%20Chaos%20Judah%20Rell',
    label: 'Original Master: “Quiet in the Chaos” (11:22)',
  },
  26: {
    audioUrl: '/audio/week_26.mp3',
    duration: 707,
    filename: 'SacredSteps_W26_Ledger_of_Light_Zaria_Lumen.mp3',
    sunoUrl: 'https://suno.com/search?q=Ledger%20of%20Light%20Zaria%20Lumen',
    label: 'Original Master: “Ledger of Light” (11:47)',
  },
  27: {
    audioUrl: '/audio/week_27.mp3',
    duration: 719,
    filename: 'SacredSteps_W27_Gates_of_Grace_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Gates%20of%20Grace%20Simone%20Reyner',
    label: 'Original Master: “Gates of Grace” (11:59)',
  },
  28: {
    audioUrl: '/audio/week_28.mp3',
    duration: 766,
    filename: 'SacredSteps_W28_Hands_That_Hold_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=Hands%20That%20Hold%20Judah%20Rell',
    label: 'Original Master: “Hands That Hold” (12:46)',
  },
  29: {
    audioUrl: '/audio/week_29.mp3',
    duration: 712,
    filename: 'SacredSteps_W29_No_More_Hiding_Kojo_Bright.mp3',
    sunoUrl: 'https://suno.com/search?q=No%20More%20Hiding%20Kojo%20Bright',
    label: 'Original Master: “No More Hiding” (11:52)',
  },
  30: {
    audioUrl: '/audio/week_30.mp3',
    duration: 854,
    filename: 'SacredSteps_W30_The_Long_Haul_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Long%20Haul%20Judah%20Rell',
    label: 'Original Master: “The Long Haul” (14:14)',
  },
  31: {
    audioUrl: '/audio/week_31.mp3',
    duration: 696,
    filename: 'SacredSteps_W31_Strength_in_the_Song_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Strength%20in%20the%20Song%20(Joy%20Rediscovered)%20Simone%20Reyner',
    label: 'Original Master: “Strength in the Song (Joy Rediscovered)” (11:36)',
  },
  32: {
    audioUrl: '/audio/week_32.mp3',
    duration: 683,
    filename: 'SacredSteps_W32_Thinking_of_Myself_Less_Eli_Hargrove.mp3',
    sunoUrl: 'https://suno.com/search?q=Thinking%20of%20Myself%20Less%20Eli%20Hargrove',
    label: 'Original Master: “Thinking of Myself Less” (11:23)',
  },
  33: {
    audioUrl: '/audio/week_33.mp3',
    duration: 719,
    filename: 'SacredSteps_W33_Iron_in_the_Fire_Marcus_Vale.mp3',
    sunoUrl: 'https://suno.com/search?q=Iron%20in%20the%20Fire%20Marcus%20Vale',
    label: 'Original Master: “Iron in the Fire” (11:59)',
  },
  34: {
    audioUrl: '/audio/week_34.mp3',
    duration: 699,
    filename: 'SacredSteps_W34_The_Bridge_of_Iron_Dre_Solace.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Bridge%20of%20Iron%20Dre%20Solace',
    label: 'Original Master: “The Bridge of Iron” (11:39)',
  },
  35: {
    audioUrl: '/audio/week_35.mp3',
    duration: 571,
    filename: 'SacredSteps_W35_Slow_Burn_Colt_Ferrin.mp3',
    sunoUrl: 'https://suno.com/search?q=Slow%20Burn%20Colt%20Ferrin',
    label: 'Original Master: “Slow Burn” (9:31)',
  },
  36: {
    audioUrl: '/audio/week_36.mp3',
    duration: 876,
    filename: 'SacredSteps_W36_Wisdom_Mose_Ardell.mp3',
    sunoUrl: 'https://suno.com/search?q=Wisdom%20Mose%20Ardell',
    label: 'Original Master: “Wisdom” (14:36)',
  },
  37: {
    audioUrl: '/audio/week_37.mp3',
    duration: 650,
    filename: 'SacredSteps_W37_Bounce_Back_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Bounce%20Back%20Simone%20Reyner',
    label: 'Original Master: “Bounce Back” (10:50)',
  },
  38: {
    audioUrl: '/audio/week_38.mp3',
    duration: 790,
    filename: 'SacredSteps_W38_Renewed_Dreams_Eli_Hargrove.mp3',
    sunoUrl: 'https://suno.com/search?q=Renewed%20Dreams%20Eli%20Hargrove',
    label: 'Original Master: “Renewed Dreams” (13:10)',
  },
  39: {
    audioUrl: '/audio/week_39.mp3',
    duration: 741,
    filename: 'SacredSteps_W39_Grace_Extended_Kojo_Bright.mp3',
    sunoUrl: 'https://suno.com/search?q=Grace%20Extended%20Kojo%20Bright',
    label: 'Original Master: “Grace Extended” (12:21)',
  },
  40: {
    audioUrl: '/audio/week_40.mp3',
    duration: 783,
    filename: 'SacredSteps_W40_Iron_The_Mirror_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=Iron%20%26%20The%20Mirror%20Judah%20Rell',
    label: 'Original Master: “Iron & The Mirror” (13:03)',
  },
  41: {
    audioUrl: '/audio/week_41.mp3',
    duration: 538,
    filename: 'SacredSteps_W41_Vessels_of_Grace_Zaria_Lumen.mp3',
    sunoUrl: 'https://suno.com/search?q=Vessels%20of%20Grace%20Zaria%20Lumen',
    label: 'Original Master: “Vessels of Grace” (8:58)',
  },
  42: {
    audioUrl: '/audio/week_42.mp3',
    duration: 741,
    filename: 'SacredSteps_W42_Unbound_Femi_Highgate.mp3',
    sunoUrl: 'https://suno.com/search?q=Unbound%20Femi%20Highgate',
    label: 'Original Master: “Unbound” (12:21)',
  },
  43: {
    audioUrl: '/audio/week_43.mp3',
    duration: 769,
    filename: 'SacredSteps_W43_The_Quiet_Dawn_Naledi_Groove.mp3',
    sunoUrl: 'https://suno.com/search?q=The%20Quiet%20Dawn%20(Routines%20of%20Grace)%20Naledi_Groove',
    label: 'Original Master: “The Quiet Dawn (Routines of Grace)” (12:49)',
  },
  44: {
    audioUrl: '/audio/week_44.mp3',
    duration: 647,
    filename: 'SacredSteps_W44_Word_of_My_Testimony_Kwame_Uplift.mp3',
    sunoUrl: 'https://suno.com/search?q=Word%20of%20My%20Testimony%20Kwame%20Uplift',
    label: 'Original Master: “Word of My Testimony” (10:47)',
  },
  45: {
    audioUrl: '/audio/week_45.mp3',
    duration: 643,
    filename: 'SacredSteps_W45_Mended_Glass_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Mended%20Glass%20Simone%20Reyner',
    label: 'Original Master: “Mended Glass” (10:43)',
  },
  46: {
    audioUrl: '/audio/week_46.mp3',
    duration: 797,
    filename: 'SacredSteps_W46_Still_Standing_Femi_Highgate.mp3',
    sunoUrl: 'https://suno.com/search?q=Still%20Standing%20Femi%20Highgate',
    label: 'Original Master: “Still Standing” (13:17)',
  },
  47: {
    audioUrl: '/audio/week_47.mp3',
    duration: 744,
    filename: 'SacredSteps_W47_This_Is_The_Day_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=This%20Is%20The%20Day%20(Milestone%20Praise)%20Judah%20Rell',
    label: 'Original Master: “This Is The Day (Milestone Praise)” (12:24)',
  },
  48: {
    audioUrl: '/audio/week_48.mp3',
    duration: 679,
    filename: 'SacredSteps_W48_Seeds_for_Tomorrow_Zaria_Lumen.mp3',
    sunoUrl: 'https://suno.com/search?q=Seeds%20for%20Tomorrow%20Zaria%20Lumen',
    label: 'Original Master: “Seeds for Tomorrow” (11:19)',
  },
  49: {
    audioUrl: '/audio/week_49.mp3',
    duration: 679,
    filename: 'SacredSteps_W49_What_it_Is_Judah_Rell.mp3',
    sunoUrl: 'https://suno.com/search?q=What%20it%20Is%20Judah%20Rell',
    label: 'Original Master: “What it Is” (11:19)',
  },
  50: {
    audioUrl: '/audio/week_50.mp3',
    duration: 902,
    filename: 'SacredSteps_W50_Unveiled_Glory_to_Glory_Simone_Reyner.mp3',
    sunoUrl: 'https://suno.com/search?q=Unveiled%20(Glory%20to%20Glory)%20Simone%20Reyner',
    label: 'Original Master: “Unveiled (Glory to Glory)” (15:02)',
  },
  51: {
    audioUrl: '/audio/week_51.mp3',
    duration: 662,
    filename: 'SacredSteps_W51_Roots_in_the_Soil_Mose_Ardell.mp3',
    sunoUrl: 'https://suno.com/search?q=Roots%20in%20the%20Soil%20Mose%20Ardell',
    label: 'Original Master: “Roots in the Soil” (11:02)',
  },
  52: {
    audioUrl: '/audio/week_52.mp3',
    duration: 778,
    filename: 'SacredSteps_W52_Miles_of_Grace_Zaria_Lumen.mp3',
    sunoUrl: 'https://suno.com/search?q=Miles%20of%20Grace%20(The%20Whole%20Story)%20Zaria%20Lumen',
    label: 'Original Master: “Miles of Grace (The Whole Story)” (12:58)',
  },
};
